### PR TITLE
Added support for custom Attributes

### PR DESCRIPTION
**Pull request by saschaarlt**
Implement the requested feature:
Custom Attributes.
https://github.com/Asesjix/Zammad.Client/issues/38

with this extension it would possible to use any custom attribute in zammad created like described in
https://admin-docs.zammad.org/en/latest/system/objects.html

on objects lik:
+ user
+ organization
+ ticket
+ group

so the full power of  add your own fields is useable

### CODE REVIEW

**Comment by saschaarlt** [comment]
usage via VB.net:
myTicket.CustomAttributes("testattribut") = "a valid string from extern"

**Comment by saschaarlt** [comment]
Hi @Asesjix,

would you like to accept our pull Request?
We would be happy to continue using your nuget package.

**Review by oiBio — CHANGES_REQUESTED** [review]
Looks and works fine for me
Maybe you should remove the changes in Zammad-Client.sln and co to get merged into main

**Comment by saschaarlt** [comment]
is it so ok?
Otherwise a detail Advice what is to do for me. Thanks. (I'm new @Github)

**Pull request closed without merging**
